### ISSUE TITLE
申请加入 Doocs 开源组织 🙋

### ISSUE THREAD

**Issue by EgoSay** [doocs/doocs.github.io#14]
申请加入 Doocs 开源组织 🙋

**Comment by yanglbme** [comment]
@EgoSay 你好，给你发邀请了，欢迎加入，访问 https://github.com/doocs 接受邀请即可。

> You've invited Ego to Doocs! They'll be receiving an email shortly. They can also visit https://github.com/doocs to accept the invitation.
