### ISSUE TITLE
加入社区以后可以挂开源库的链接到社区么？

### ISSUE THREAD

**Issue by SylarLong** [doocs/doocs.github.io#153]
RT

**Comment by yanglbme** [comment]
想怎么挂

**Comment by SylarLong** [comment]
@yanglbme 
像这样？😂 
![image](https://github.com/doocs/doocs.github.io/assets/6510425/5382a4fc-7811-4882-991a-54a7a1e7711e)

**Comment by yanglbme** [comment]
这里的项目，需要是在 doocs 下的，个人的项目不适合放这里

**Comment by SylarLong** [comment]
明白了，只是随口问一下，感谢解答，要是有个地方能挂成员的项目就好了😊
