### ISSUE TITLE
申请加入 Doocs GitHub 组织

### ISSUE THREAD

**Issue by ThisIs-Developer** [doocs/doocs.github.io#204]
你好 Doocs 团队，

I’m interested in joining the Doocs GitHub organization. I have 2 years of experience in Java and strong JavaScript skills.

GitHub Profile: github.com/ThisIs-Developer

感谢您考虑我的申请。

期待您的回复，  
ThisIs-Developer

**Comment by yanglbme** [comment]
Hi @ThisIs-Developer 

I've sent you an invitation. Please visit https://github.com/doocs to accept it. Welcome to the Doocs team! 😊

**Comment by ThisIs-Developer** [comment]
谢谢
